android.useAndroidX=true
android.enableJetifier=true
kotlin.code.style=official
org.gradle.jvmargs=-Xmx10240m -Dfile.encoding=UTF-8
org.gradle.caching=true
org.gradle.parallel=false
org.gradle.workers.max=2
kotlin.compiler.execution.strategy=in-process
android.suppressUnsupportedCompileSdk=35
VERSION_NAME=0.9538
MOBILE_VERSION_CODE=95380
WEAR_VERSION_CODE=95381
